spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    hibernate:   # A primeira vez tenho que colocar como create e depois voltar para validate
      ddl-auto: validate # validate | update | create | delete